### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by ligi** [livepeer/file-video#18]
When uploading a video (that is smaller than 30MB) I am getting this:

![file video - Brave_372](https://user-images.githubusercontent.com/111600/103482244-12e5df80-4de0-11eb-88c0-0237bf3fa415.png)

**Comment by ramiz4** [comment]
The file must be smaller than 30 MB. The problem is most likely due to the fact that the backend service https://demux.onrender.com is no longer available...

**Comment by rajdeepbharati** [comment]
@ligi We are looking into the issue in the backend service

**Comment by rajdeepbharati** [comment]
The issue has been resolved now (it was due to an upgrade in a dependency)

**Comment by ligi** [comment]
Is the change rolled out? Still seeing this

**Comment by rajdeepbharati** [comment]
Yup, it has been rolled out. Do you mind doing a hard reload of the webpage (eg: cmd+shift+r or ctrl+shift+r) then trying to upload the video again?

**Comment by chrishobcroft** [comment]
@rajdeepbharati this also doesn't work for me. Also still seeing "Failed to fetch".

Maybe you want to re-open this issue until it is confirmed as being resolved.

**Comment by chrishobcroft** [comment]
I am able to replicate this on Chrome and Brave on Android, and Brave on Ubuntu.

**Comment by rajdeepbharati** [comment]
@chrishobcroft could you share the file which you uploaded? Also, does the upload fail every time for you?

**Comment by rajdeepbharati** [comment]
Hello, we were facing a cache invalidation issue in the server, due to which the service was failing. It now seems to be resolved. Could you try it out again, and let us know if you're still facing any problems?

**Comment by ramiz4** [comment]
Now it works for me...
